export enum Paths {
  UPLOAD_FILE = '/upload-file',
  REGISTER_COSTUMER = '/register-costumer',
  LOGIN_COSTUMER = '/login-costumer',
  LOGIN_ADMIN = '/login-admin',
  REGISTER_AGENT = '/register-agent',
  FORGOT_PASSWORD = '/forgot-password-customer',
  ADD_CATEGORY_SUBCATEGORY = '/create-category-subcategory',
  UPDATE_CATEGORY_SUBCATEGORY = '/update-category-subcategory',
  FORGOT_PASSWORD_ADMIN = '/forgot-password-admin',
  RESET_PASSWORD = '/reset-password',
  RESET_PASSWORD_ADMIN = '/reset-password-admin',
  GET_ALL_CATEGORY = '/get-all-category',

  DELETE_CATEGORY = '/delete-category',
  CREATE_PRODUCT_VARIANTS = '/create-product-variants',
  CREATE_PRODUCT='/create-product' ,
  ADD_PRODUCT_VARIANTS = '/add-product-variants',
  CREATE_OPTIONS_SUBOPTIONS = '/create-options-suboptions',
  DELETE_OPTION_SUBOPTION = '/delete-option-suboptions',
  DELETE_PRODUCT_VARIANT = '/delete-product-variants',
  ADD_SUB_OPTIONS = '/create-suboptions',
  DELETE_SUBOPTION = '/delete-suboptions',
  UPDATE_SUBOPTION = '/update-subOption',
  UPDATE_PRODUCT_VARIANTS = '/update-product-variants',
  UPDATE_OPTION = '/update-option',
  UPDATE_PRODUCT = '/update-product',
  DELETE_PRODUCT = '/delete-product',
  GET_ALL_OPTIONS = '/getAll-option',
  GET_SUBOPTION_By_OPTION = '/get-suboption-by-option',
  GET_PRODUCT_WITH_VARIANTS = '/Get-product-with-variants',

  GET_ALL_VARIANT_BY_PRODUCT = '/get-all-variant-by-product',
  GET_ALL_PRODUCT_BY_CATEGORIE = '/get-all-product-by-category',
  UPDATE_PRODUCT_Categries = '/update-productCategries',
  CREATE_CUSTOMER_ADRESS = '/create-customer-address',
  UPDATE_CUSTOMER_ADRESS = '/update-customer-address',
  DELETE_CUSTOMER_ADRESS = '/delete-customer-address',
  UPDATE_PERSONAL_INFORMATION_COSTUMER = '/update-personal-information-costumer',
  GET_CURRENT_USER = '/get-current-user',
  SEND_EMAIL_NEWS_LETTER = '/news-letter',
  CHANGE_PASSWORD_COSTUMER = '/change-password',

  GET_ALL_ADDRESS = '/get-all-address',
  CREATE_NEW_MENU_ITEM = '/create-new-menu-item',
  CREATE_NEW_PRIVULEGE = '/create-new-privilege',
  AFFECT_PRIVILEGE_TO_AGENT = '/affect-privilege-to-agent',
  GET_AGENT_ACCESS = '/get-agent-access',
  UPDATE_PRIVILEGE = '/update-privilege',
  GET_ALL_PRODUCT = '/get-all-products',
  GET_ALL_ORDERS = '/get-all-orders',
  UPDATE_ORDER_STATUS = '/update-order-status',
  CHANGE_PASSWORD_ADMIN = '/change-password',
  UPDATE_PERSONAL_INFORMATION = '/update-personal-information',
  GET_ALL_RETURNS = '/get-all-returns',
  CREATE_ORDER = '/create-order',
  GET_RETURNED_ORDER = '/get-returned-order-details',
  CREATE_NEW_RETURN = '/create-new-return',
  GET_USER_INFORMATION = '/get-user-information',
  LOAD_FILE = '/load-file-product',
//admin links
  GET_LIST_PRODUCT = '/wind-stock/products',
  ADD_PRODUCT='/wind-stock/products/create' ,
  GET_PRODUCT_IMAGE = '/wind-stock/products/loadFile/',
  GET_ALL_PRODUCT_IMAGES = '/all-products-images',
  GET_PRODUCT_BY_CATEGORY = '/wind-stock/products/getByCategoryId/',
  GET_LIST_OPTIONS = '/wind-stock/product-options/getAll',
  CREATE_OPTION = '/wind-stock/product-options/create',
  GET_SUBOPTION_BY_OPTION = '/wind-stock/sub-options/getAllByOptions/',
  GET_ALL_OPTION = '/wind-stock/product-options/getAll',
  GET_ALL_CATEGORIES = '/wind-stock/category/getAll',
  DELETE_CATEGORIES = '/wind-stock/category/',
  DELETE_SUBOPTIONS = '/wind-stock/sub-options/',
  REMOVE_OPTION='/wind-stock/product-options/' ,
  WIND_AUTH = '/wind-auth',
  CHANGE_PASSWORD='/wind-auth/users/update-password/' ,
  CREATE_SUB_OPTION = "/wind-stock/sub-options/create",
  CREATE_CATEGORY = "/wind-stock/category/create",
  UPDATE_CATEGORY="/wind-stock/category/update" ,

  //custumer Links
  GET_PRODUCT_BY_ID = '/wind-stock/products/getId/',

  //*************** Custumer links********************** */

  GET_ALL_PRODUCTS = "/get-all-products-by-category",
  GET_ALL_PARENT_CATEGORY = '/get-all-parent-category',
  GET_PRODUCT_DEATAILS_BY_ID= '/get-products-by-id'
}
